### ISSUE TITLE
Error in abind::abind(landmarksArray, landmarksArray1, along = 3)

### ISSUE THREAD

**Issue by Humminglipe** [StevenVB12/patternize#34]
Hello Steven! 

I'm trying to reproduce the code to analyze some birds photos. But I got an error when trying to do the alignment of the images, here's the code

IDlist <- tools::file_path_sans_ext(dir("D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/PNG", ".png"))
imageList <- makeList(IDlist, type = "image", prepath = "D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/PNG", extension = ".png")
listaLandmarks <- makeList(IDlist, type = "landmark", prepath = "D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/Landmarks", extension = ".txt")
target <- listaLandmarks[['DSC_0067']]
mask <- read.csv("D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/Mascaras/DSC_0067_mask.txt", header = FALSE)

imageList_aligned <- alignLan(imageList, listaLandmarks, transformRef = target, adjustCoords = TRUE, plotTransformed = 5, cartoonID = 'DSC_0067', maskOutline = mask, inverse = FALSE)

[1] "sample 1 DSC_0065 added to array"
[1] "sample 2 DSC_0067 added to array"
Error in abind::abind(landmarksArray, landmarksArray1, along = 3) :
can only supply one list-valued argument for ...

Don't know if its an error on the files,

I'll appreciate your help, 

Thanks! 
All my best, Felipe

**Comment by StevenVB12** [comment]
Hi Felipe,

I’ve heard about this error a couple of times now. It occurs for R version 4.2.1 and I pushed an update that github that should fix it. Could you either revert back to R4.1.1 or update patternize through github and let me know if you still get the error?

Thanks,

Steven

From: Humminglipe ***@***.***>
Sent: Thursday, September 15, 2022 6:27 PM
To: StevenVB12/patternize ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StevenVB12/patternize] Error in abind::abind(landmarksArray, landmarksArray1, along = 3) (Issue #34)


Hello Steven!

I'm trying to reproduce the code to analyze some birds photos. But I got an error when trying to do the alignment of the images, here's the code

IDlist <- tools::file_path_sans_ext(dir("D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/PNG", ".png"))
imageList <- makeList(IDlist, type = "image", prepath = "D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/PNG", extension = ".png")
listaLandmarks <- makeList(IDlist, type = "landmark", prepath = "D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/Landmarks", extension = ".txt")
target <- listaLandmarks[['DSC_0067']]
mask <- read.csv("D:/Proyecto de tesis/Imagenes/Recolorize/Ramphocelus/Mascaras/DSC_0067_mask.txt", header = FALSE)

imageList_aligned <- alignLan(imageList, listaLandmarks, transformRef = target, adjustCoords = TRUE, plotTransformed = 5, cartoonID = 'DSC_0067', maskOutline = mask, inverse = FALSE)

[1] "sample 1 DSC_0065 added to array"
[1] "sample 2 DSC_0067 added to array"
Error in abind::abind(landmarksArray, landmarksArray1, along = 3) :
can only supply one list-valued argument for ...

Don't know if its an error on the files,

I'll appreciate your help,

Thanks!
All my best, Felipe

**Comment by Humminglipe** [comment]
Thanks for your response Steve,
I tried both options, none of them worked. 
The same issue stills appearing

**Comment by StevenVB12** [comment]
I think I fixed the problem. Could you please download again through Github and let me know.

Thanks,

Steven

**Comment by StuntsPT** [comment]
I had the same issue, but I can confirm that using the latest `master` solves the problem for me!
So I guess [bcb0f02](https://github.com/StevenVB12/patternize/commit/bcb0f02055f9bafd24b67b0143e3fe0d902b6b33) fixes the issue?
Thank you very much for looking into it!

Best,

Francisco

**Comment by Humminglipe** [comment]
It worked! Thanks Steven!

**Comment by C-G-L** [comment]
Hi Im still getting the same issue. I am on R 4.2.1, working with the sample data, and getting the abind error. I've uninstalled and reinstalled from github but to no avail.

**Comment by StevenVB12** [comment]
Could you share me your files and script for me to troubleshoot?

Many thanks,

Steven


-------- Original message --------
From: C-G-L ***@***.***>
Date: 9/26/22 8:12 PM (GMT+01:00)
To: StevenVB12/patternize ***@***.***>
Cc: "Steven M. Van Belleghem" ***@***.***>, Comment ***@***.***>
Subject: Re: [StevenVB12/patternize] Error in abind::abind(landmarksArray, landmarksArray1, along = 3) (Issue #34)


Hi Im still getting the same issue. I am on R 4.2.1, working with the sample data, and getting the abind error. I've uninstalled and reinstalled from github but to no avail.

**Comment by C-G-L** [comment]
Fixed it! I had to reinstall some packages to get it to work. I dont really know what the problem was. Thanks for the quick response Steven. Much appreciated!

**Comment by StevenVB12** [comment]
Fantastic. Thanks for letting me know!

Steven

**Comment by aphanotus** [comment]
Hello, Steven. First, thanks for developing this package. I am excited to try it out for several projects. Someone I am teaching with introduced it to our students, and unfortunately we encountered this error too. so I am trying to sort it out. I've made sure we're all using the latest GitHub versions of patternize, raster, abind, etc. However, we all get the same error referencing abind. 

I tried implementing the [fix](https://github.com/StevenVB12/patternize/commit/bcb0f02055f9bafd24b67b0143e3fe0d902b6b33) noted above manually and then assigning the modified function to the patternize namespace. However, this led to another issue 
```
Error in x$.self$finalize() : attempt to apply non-function
In addition: Warning messages:
1: [rast] unknown extent 
2: [rast] unknown extent 
3: [rast] unknown extent 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'extent': incorrect number of dimensions
```
So I've reached the end of what I think I can try. Any advice?

**Comment by StevenVB12** [comment]
Hi Dave,

Sorry you’re still experiencing problems. Would you mind sharing me your code and some of your images? I will try running it on my end first to see everything works fine or not.

Best wishes,

Steven
